# Generated by Django 4.1.3 on 2023-03-03 19:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('PGapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelEmployees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Employee first name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Employee last name')),
                ('birth_date', models.DateField(verbose_name='Employee birth date')),
                ('address', models.CharField(max_length=100, verbose_name='Employee address')),
                ('hire_date', models.DateField(auto_now=True, verbose_name='Employee hire date')),
                ('phone', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Employee phone')),
                ('photo', models.ImageField(blank=True, default='D:/A_PYTHONPROJECTS/Revashing/folder/PGsite/media/img/default.jpg', error_messages={'invalid_extension': 'This format is not allowed'}, null=True, upload_to='img/Employee_pics/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'jpeg', 'png'))], verbose_name='Employee Photo')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
        migrations.CreateModel(
            name='HotelRooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=90, verbose_name='Room Title')),
                ('picture', models.ImageField(blank=True, default='D:/A_PYTHONPROJECTS/Revashing/folder/PGsite/media/img/room_default.png', error_messages={'invalid_extension': 'This format is not allowed'}, null=True, upload_to='img/Hotel_Room_pics/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'jpeg', 'png'))], verbose_name='Room Picture')),
                ('picture_thumbnail', easy_thumbnails.fields.ThumbnailerImageField(default='D:/A_PYTHONPROJECTS/Revashing/folder/PGsite/media/img/room_thumbnail_default.png', upload_to='img/Hotel_Room_thumbnails/%Y/%m/%d/')),
                ('price', models.IntegerField(verbose_name='Room Price')),
                ('description', models.TextField(verbose_name='Room Description')),
            ],
            options={
                'verbose_name': 'Hotel Room',
                'verbose_name_plural': 'Hotel Rooms',
            },
        ),
        migrations.CreateModel(
            name='PGSThing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hierarchy', models.IntegerField(verbose_name='Hierarchy')),
            ],
            options={
                'verbose_name': 'Thing',
                'verbose_name_plural': 'Things',
                'ordering': ['thing_itself'],
            },
        ),
        migrations.DeleteModel(
            name='PGSRoomReserving',
        ),
        migrations.AlterModelOptions(
            name='pgsrubric',
            options={'get_latest_by': 'rubric', 'ordering': ['rubric'], 'verbose_name': 'Rubric', 'verbose_name_plural': 'Rubrics'},
        ),
        migrations.RenameField(
            model_name='pgsrubric',
            old_name='name',
            new_name='rubric',
        ),
        migrations.AddField(
            model_name='pgsthing',
            name='thing_itself',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PGapp.pgsrubric'),
        ),
    ]
